title: 준민 블로그
logo: /assets/img/MokokoLogo.png
email: jm980513@gmail.com
description: 깃블로그 테스트 페이지입니다.
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
